name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        uses: ./
        with:
          data-directory: './data'
          id: 'smartcity-data-platform-upload-action-test'
          shapefile-default-crs: 'EPSG:2446'
          api-key: ${{secrets.GEOLONIA_DATA_PLATFORM_API_KEY}}
